# Generated by Django 5.0.1 on 2024-01-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_alter_women_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='content',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='women',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
