# Generated by Django 5.0.1 on 2024-02-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0008_uploadfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo'),
        ),
    ]
